name: Deploy HTML to AWS S3

on:
  push:
    branches:
      - main  # Runs when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetches latest code

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # ✅ Secure
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # ✅ Secure
          aws-region: eu-north-1

      - name: Upload Files to AWS S3
        run: |
          aws s3 sync . s3://my-static-site-bucket --delete
